[package]
name = "bitcoind"
version = "0.8.4"
edition = "2021"
description = "A Rust library for managing Bitcoin Core nodes in Docker containers"
license = "MIT"
repository = "https://github.com/fairgateLabs/rust-bitcoind"
keywords = ["bitcoin", "docker", "bitcoind", "blockchain"]
categories = ["development-tools"]
readme = "README.md"

[dependencies]
bollard = "0.21.1"
bitvmx-bitcoin-rpc = { git = "https://github.com/FairgateLabs/rust-bitvmx-bitcoin-rpc.git", tag = "v0.8.4" }
futures-util = "0.3"
tokio = { version = "1.53.1", features = ["sync", "rt-multi-thread"] }
tracing = "0.1"
thiserror = "2.0.20"
serde = { version = "1.0.229", features = ["derive"] }

[dev-dependencies]
bitcoin = "0.32.102"
redact = { version = "0.1", features = ["serde"] }
